### ISSUE TITLE
To cancel orders in hours

### ISSUE THREAD

**Issue by svaldesm** [rvola/woo-cancel-abandoned-order#1]
Hi! Sorry, this is not an issue but I wanted to ask this. I will delete it once I have the answer.
Thanks!

**Comment by rvola** [comment]
Hello @svaldesm !

Now YES ! 😉
https://github.com/rvola/woo-cancel-abandoned-order/releases/tag/1.3.0 (available on the WP Repository)

If you can give me a [good rating here](https://wordpress.org/support/plugin/woo-cancel-abandoned-order/reviews/#new-post), thank you.

**Comment by svaldesm** [comment]
Hi there! Thanks for the awesome plugin.
I was wondering, is there an easy way to change days per hours?
I tried checking the code but it's not clear.

Thank you very much.


Santiago Valdés M.

**Comment by rvola** [comment]
hello Santiago!

I will look at that when I have a moment ;)

**Comment by svaldesm** [comment]
Hi!

This might seem like a joke, but the auto restocking is causing me issues because I have another plugin for that which is more broad. Basically, right now the other plugin takes care of every cancelled order. The problem is that your plugin only does for on-hold, but the other does it on every cancelled order. So right now basically I'm restocking 2 times. 
Is there a way to return to the last version or at least have an option to use or not use the restocking?

Thanks a lot!

**Comment by rvola** [comment]
Arf 😂
Just uncheck the option "restock" in the settings of the extension in "Check"

**Comment by svaldesm** [comment]
![image](https://media.giphy.com/media/6yRVg0HWzgS88/giphy.gif)

Wow. So sorry. I completely forgot there was that options page. Thanks!

**Comment by svaldesm** [comment]
Hi there. Me again. 
Seems like this plugin might be conflicting with other plugins. I'm trying to debug what's going on.

The original stock number is 1. When the purchase is done, stock goes down to 0. 
When the order gets canceled after 3 days, stock increases to "2". 
I have disabled the option to restock because another plugin takes care of that (I use it for other payment methods too).

Is it possible that the option to restock is working even thought it's disabled?

**Comment by rvola** [comment]
Hi @svaldesm !

Normally here, we check that the option is "yes". He should not have any problems. ([here](https://github.com/rvola/woo-cancel-abandoned-order/blob/f72c34df71485ae8b41cf4454724965088367432/includes/class-cao.php#L129))

This value is stored serialized in the wp_options table with this name: **woocommerce_% account_type%_settings**.
_Replaces %account_type% with payment type (eg 'check')_

Looking, I see that the value changes between 'yes' and 'no' on my side.
Do you know that this option is present in every type of payment you use?

**Comment by svaldesm** [comment]
Hi Nicolas,

I think I realized what the issue was. It was not related to this. Thanks
for your explanation!

Santiago Valdés M.

**Comment by rvola** [comment]
Enjoy [**1.4.0**](https://github.com/rvola/woo-cancel-abandoned-order/releases/tag/1.4.0)
