### ISSUE TITLE
canceled orders mailed to multiple clients

### ISSUE THREAD

**Issue by immunity20** [rvola/woo-cancel-abandoned-order#10]
for example order1 of client 1 and order 2 of client2
after firing cron job for cao
client1 and client2 received 2 emails (one for order1 and one for order2)

**Comment by rvola** [comment]
Hello @immunity20 !

I just did a test with 2 pending commands, and I asked for the execution now of woo_cao_cron by the WP-Crontrol plug-in.

The plug-in has canceled orders and sent 1 email to each customer.

Can you explain to me more what happened and how you did it?

**Comment by immunity20** [comment]
Sorry, it was another plugin that created this issue (plugin to send cancelled order emails also to clients it was using email_receivers **.=** order's billing_email

**Comment by rvola** [comment]
😅👍
