### ISSUE TITLE
Prevent order cancellation for the past

### ISSUE THREAD

**Issue by dademaru** [rvola/woo-cancel-abandoned-order#13]
Hello,

thanks for your plugin. I gave it a try and works perfectly. 

I wonder if it's possible to **prevent order cancellation for the past** and then to enable it **only for future orders**.
E.g. a store owner has hundreds of on-hold orders he forgot to cancel. 
However, over time he has manually updated the inventory.
He wants to prevent the cancellation of past orders from restoring the stock, altering the actual current stock, and from triggering several emails.

Do you thing it's possible to add this option?
Thanks

**Comment by rvola** [comment]
Hi @dademaru 
Yes it is already possible using the filter
**woo_cao_before_cancel_order**: Before canceling the order, send the order_id and the WC_Order if you do not want to cancel this order. Expect an exact return of true.
https://github.com/rvola/woo-cancel-abandoned-order/blob/master/includes/class-cao.php#L171

**Comment by dademaru** [comment]
Hi @rvola,
thanks. 
Just after opening the issue I inspected your code and found exactly that hook ;-)

This is the solution I've used:

```
add_filter( 'woo_cao_before_cancel_order', 'com_woo_cao_skip_past_orders', 10, 3 );
/**
 * Skip past orders.
 *
 * @param  bool		$cancel   	Default: true.
 * @param  int 		$order_id
 * @param  WC_Order	$order
 * @return bool
 */
function com_woo_cao_skip_past_orders( $cancel, $order_id, $order ) {
	$present  = new DateTime( '2021-01-01' );
	if ( $order->get_date_created()->getTimestamp() < $present->getTimestamp() ) {
		return false;
	}
	return $cancel;
}
```

**Comment by rvola** [comment]
well done !
