### ISSUE TITLE
How to troubleshoot...

### ISSUE THREAD

**Issue by melrazdig** [rvola/woo-cancel-abandoned-order#14]
Hi, I want to change the status of 'Failed' orders to 'Cancelled' after 1 hour. I have added the following to functions.php but my test failed order doesn't change to cancelled. I have also enabled it on the payment Gateway. What am I doing wrong?

function woa_custom_gateways_hook( $gateways ) {
     $gateways[] = 'paymentsense_direct'; 
     return $gateways;
}
add_filter( 'woo_cao_gateways', 'woa_custom_gateways_hook', 10, 1 );

function woa_custom_statustocancel_hook( $status ) {
	$status[] = 'wc-failed';
	return $status;
}

add_filter( 'woo_cao_statustocancel', 'woa_custom_statustocancel_hook', 10, 1 );

**Comment by rvola** [comment]
Hello,
I indicated on the WordPress forum that I no longer provide support on the custom configuration.

Your given configuration looks good.
