### ISSUE TITLE
Not really working with automatic payments with some gates

### ISSUE THREAD

**Issue by bielu** [rvola/woo-cancel-abandoned-order#3]
Hi Guys,
As I am developer I figure out what should be done to make sure will work with some gates with using "wc-pending" status instead of "wc-on-hold" :) I changed includes/class-cao.php:
`SELECT posts.ID
							FROM $wpdb->posts as posts
							INNER JOIN $wpdb->postmeta as meta
							ON posts.ID = meta.post_id
							WHERE posts.post_type = 'shop_order'
							AND posts.post_status = 'wc-on-hold'
							AND posts.post_date < %s
							AND meta.meta_key = '_payment_method'
							AND meta.meta_value = %s`
to
`SELECT posts.ID
							FROM $wpdb->posts as posts
							INNER JOIN $wpdb->postmeta as meta
							ON posts.ID = meta.post_id
							WHERE posts.post_type = 'shop_order'
							AND (posts.post_status = 'wc-pending' OR posts.post_status ='wc-on-hold')
							AND posts.post_date < %s
							AND meta.meta_key = '_payment_method'
							AND meta.meta_value = %s`

I hope I helped you :) 
Cheer,
Arkadiusz

**Comment by rvola** [comment]
Hello @bielu 

There was no problem at this level. The purpose of the extension (at the beginning) is to cancel the "on-hold" commands.
The status "waiting" is when an order is pending payment. Usually with a credit card.

If it will ever be wiser to use IN

`SELECT posts.ID FROM $wpdb->posts as posts INNER JOIN $wpdb->postmeta as meta ON posts.ID = meta.post_id WHERE posts.post_type = 'shop_order' AND posts.post_status IN ('wc-pending','wc-on-hold') AND posts.post_date < %s AND meta.meta_key = '_payment_method' AND meta.meta_value = %s `

I do not know if I have to change that.

**Comment by rvola** [comment]
I am waiting for a return of a request on the forum.
In a future version if it is validated, it would be possible to modify the SQL request.

https://github.com/rvola/woo-cancel-abandoned-order/commit/4aed0ba106735d9f4f46f2530ac5e392ef5ee1e4
