### ISSUE TITLE
Cron that cancels orders stops working randomly

### ISSUE THREAD

**Issue by svaldesm** [rvola/woo-cancel-abandoned-order#5]
Hi guys. I created this issue without being 99% certain that the error is due to this plugin, but I wanted to ask you in case you knew how to debug this further.

I have your plugin, with the hook setup so it cancels failed and on-hold orders after 3 days. That seems to be working fine. 
The issue is related to WC automatic cancel of pending orders. It works at times, and suddenly it stops working. I have to go to Settings > Products > Inventory and save the settings, that way the cron is scheduled again.

I've checked WC changelog to see if this was a bug, but I found nothing. I check on my logs without any further debugging information. My server has no automatic restarts, on New Relic APM response time is 600ms, and the site works great, EXCEPT for this thing. 

I was wondering, considering you have experience in this specific topic, if you could guide me on how to debug this further. I don't intend that you fix me the issue and I know this is not the relevant place, but I'm a bit desperate. What happens if the orders are not cancelled is that the products are displayed as in stock, but when you try to purchase them, it won't work. 

I've read many topics of this, but none is very helpful. The main issue is that it works for some time, but then something happens and it stops working without further notice. The crons are working, otherwise your plugin won't cancel orders. It's as if somehow the cron gets removed from the scheduled tasks.

Sorry if this seems inappropriate, I'm just looking for any kind of help.
Thanks in advance,

Santiago

**Comment by rvola** [comment]
Hello @svaldesm 

Normally the task cron who deals with the treatment of this plugin is called "woo_cao_cron"

It can be easily identified using an extension like "[WP Crontrol](https://fr.wordpress.org/plugins/wp-crontrol/)"

This task is in program to run continuously.
I think maybe I know where the worry comes from.
As an old WordPress user I know that Cron is triggered by the use of the site. If the one is not too visited or there is not much action in admin, "he falls asleep"
https://www.google.com/search?q=wordpress+cron+not+executing

I advise you to add a cron on your server (ssh or interface) that runs the "wp-cron.php" file located at the root of your WordPress.
Normally at first, you should not have any problem with order processing anymore.

Come back tell me news

**Comment by svaldesm** [comment]
Hi Nicolas, thanks a lot for your answer. 
I do have a cron set up on my server and it works. I have disabled WP_CRON from wp-settings.php and operate only with this cron at server level. In any case, our site does get a lot of traffic, so that wouldn't be an issue. 

Then cron is set up as this:
`*/5 * * * * wget -q -O - https://www.domain.com/wp-cron.php`

I think it does work fine because other crons work as expected (like your plugin), that is why I was asking about cache. The cancel pending orders cron, from WC core, doesn't work.

I have Varnish and WP Rocket, but from WP Rocket team they say it doesn't have anything to do with them, so I'm left with (probably) a Varnish or other issue that I'm unable to debug. 

If you have any other idea of where can this be coming from (apart from the cron) I would really appreciate it. 

Thanks

**Comment by rvola** [comment]
sorry i am not native english.
Can you explain the problem to me again because I did not totally understand.

**Comment by svaldesm** [comment]
Sorry, I'm not a native either :) 

The issue is that the cron that cancels the orders, `woocommerce_cancel_unpaid_orders` stops working randomly on my site. 

To "fix" it, I have to go to Settings > Products > Inventory and save the settings, that way the cron is scheduled again.

I've tried several theories:
1) **Crons are not working**: this is false because other crons work as expected, so it's something related specifically to this particular cron. Also, I have an external cron task setup at the server level, so it's not dependent on the app visitors.
2) **Server crashing**: according to the logs, there is no crash that is affecting this cron.

So, I'm stuck without many answers on how to debug this. 
Is it more clear now?

Thanks!

**Comment by rvola** [comment]
ok, so I do not handle this cron.
And I can assure you 100% that my cron does not handle the cron of WooCommerce.
It uses a SQL query + order processing that needs.

Do you contact Woocommerce about this?

**Comment by svaldesm** [comment]
Yes, I've posted on the support forum.

Probably this has nothing to do with your plugin, so I'll close the issue. But anyway, how would you debug this further? So I can explore other solutions to the problem.

Thanks!

**Comment by rvola** [comment]
Hi @svaldesm 
Can your close the issue ?
