### ISSUE TITLE
How to use This Plugin ?

### ISSUE THREAD

**Issue by s-espriz** [rvola/woo-cancel-abandoned-order#6]
Hi 
im so sorry but i couldn't undrestand how should i use this plugin 

for example i want to use this plugin for all my gateways and i want to cancel 'pending' orders after '1' hour

**Comment by rvola** [comment]
The documentation is quite complete on this subject.

You must for each gateway, allow the plugin. Procedure here: https://github.com/rvola/woo-cancel-abandoned-order/wiki/Add-a-new-gateway

Then set for each gateway in Woocommerce settings, the following setting:
Mode: hourly
Time: 1 hour

By default the plugin will cancel the commands "on-hold", if however you want to cancel another status, the documentation explains it here: https://github.com/rvola/woo-cancel-abandoned-order/wiki/ Change-the-status-type-for-the-cancellation-process

Good luck
